server:
  port: 8181

spring:
  datasource:
    username: root
    password: 1012Benq86
    url: jdbc:mysql://localhost:3306/tasklist?currentSchema=tasklist&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  sql:
    init:
      mode: always
      continue-on-error: false
security:
  jwt:
    secret: cXd1aGpzZmhkeWZiY2p3ZXdqZmJkamZkamZqZEVXRUZGREZOREpG
    access: 3600000
    refresh: 2592000000
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true